controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    omnidirectional_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

omnidirectional_controller:
  ros__parameters:
    joints:
      - fr_wheel_joint
      - fl_wheel_joint
      - r_wheel_joint
    interface_name: velocity
